Add tadp tests
ActioFRM/postman pull request #12
Opened 2021-11-04 12:15 UTC by theolextego

2021-11-09 03:26 UTC, uche-lextego approved these changes

2021-11-09 08:15 UTC, jonty-esterhuizen commented
not all of the testing Testing Approach are met on 
https://lextego.atlassian.net/browse/AM-656
please make sure that all of the tests are included

2021-11-10 07:22 UTC, johanfol requested changes

2021-11-10 07:22 UTC, johanfol commented on TADProc-Tests.postman_collection.json
> +					"raw": "{\n    \"transaction\": {\n        \"TxTp\": \"pain.001.001.11\",\n        \"CstmrCdtTrfInitn\": {\n            \"GrpHdr\": {\n                \"MsgId\": \"2669e349-500d-44ba-9e27-7767a1
please replace https://frmfaas.sybrin.com with http://gateway.openfaas:8080 (even in the network sub-map) for ALL future tests..........................

2021-11-15 08:05 UTC, johanfol approved these changes

2021-11-15 08:06 UTC, merged