Add pacs002 e2e tests
ActioFRM/postman pull request #14
Opened 2021-11-10 13:28 UTC by theolextego

2021-11-11 07:19 UTC, uche-lextego commented
@theolextego , the typology host should use the gateway URL. I probably need to update mine too. 😄

2021-11-11 07:19 UTC, uche-lextego requested changes
@theolextego , the typology host should use the gateway URL. I probably need to update mine too. 😄

2021-11-11 13:18 UTC, uche-lextego commented on CRSP-Tests.postman_collection.json
> +							"                                \"host\": \"https://frmfaas.sybrin.com/function/off-typology-processor\",",
I've seen the comment functionality @theolextego

2021-11-11 13:28 UTC, uche-lextego approved these changes
LGTM

2021-11-12 08:30 UTC, johanfol approved these changes

2021-11-12 08:43 UTC, merged