add rule 018 tests
ActioFRM/postman pull request #26
Opened 2021-12-02 23:43 UTC by theolextego

2021-12-03 07:44 UTC, johanfol requested changes

2021-12-03 07:44 UTC, johanfol commented on Rule018Tests.postman_collection.json
> +					"raw": "{\n  \"transaction\": {\n    \"TxTp\": \"pacs.002.001.12\",\n    \"FIToFIPmtSts\": {\n      \"GrpHdr\": {\n        \"MsgID\": \"ec3a6a10-0c31-4564-94f6-ed1d79fed91f\",\n        \"CreDtTm
Please use internal names instead of external

2021-12-03 08:03 UTC, uche-lextego approved these changes
LGTM

2021-12-07 12:10 UTC, jonty-esterhuizen requested changes

2021-12-07 12:10 UTC, jonty-esterhuizen commented on Rule018Tests.postman_collection.json
> +							"        url: 'https://frmarango.sybrin.com/_db/transactionHistory/_api/cursor',",
this needs to internal urls

2021-12-07 12:10 UTC, jonty-esterhuizen commented on Rule018Tests.postman_collection.json
> +							"        url: 'https://frmarango.sybrin.com/_db/transactionHistory/_api/cursor',",
http://arango.development:8529/

2021-12-07 14:08 UTC, jonty-esterhuizen approved these changes

2021-12-08 11:40 UTC, johanfol approved these changes

2021-12-08 12:39 UTC, merged