test
ActioFRM/postman pull request #42
Opened 2022-01-17 13:09 UTC by Jude-lextego

Hi @joeygoksu @JBornman @uche-lextego @Ayo-lextego @johanfol @kjw000 
Kindly help review this PR for rule-016 test

2022-01-18 07:50 UTC, johanfol requested changes

2022-01-18 07:50 UTC, johanfol commented on Rule-016 Tests.postman_collection.json
> +          "raw": "{\r\n    \"transaction\": {\r\n        \"TxTp\": \"pacs.002.001.12\",\r\n        \"FIToFIPmtSts\": {\r\n            \"GrpHdr\": {\r\n                \"MsgId\": \"30bea71c5a054978ad0
Please commit using the internal names, not external ones. eg, https://frmfaas.sybrin.com->http://gateway.openfaas:8080

2022-01-18 13:30 UTC, johanfol approved these changes

2022-01-18 13:43 UTC, vorsterk approved these changes
Looks good

2022-01-19 04:34 UTC, uche-lextego approved these changes
LGTM

2022-01-19 11:08 UTC, merged