Postman Tests for Rule008
ActioFRM/postman pull request #65
Opened 2022-02-22 15:14 UTC by vorsterk

2022-02-25 06:43 UTC, johanfol approved these changes

2022-02-25 09:29 UTC, uche-lextego commented on Rule-008 Tests.postman_collection.json
> +							"    TxSts: \"ACCC\",\r",
Welldone @vorsterk on this postman tests. Why does your Pacs008 edges have Txsts????

2022-02-25 09:31 UTC, uche-lextego requested changes
Hello @vorsterk , welldone on this task. Please find the comments I made on removing Txsts from your pacs008 edges seeds.

2022-02-25 09:31 UTC, uche-lextego commented on Rule-008 Tests.postman_collection.json
> +							"    TxSts: \"ACCC\",\r",
Here too????

2022-02-26 05:39 UTC, uche-lextego approved these changes
LGTM

2022-03-03 14:16 UTC, merged