Rule 048 postman testing
ActioFRM/postman pull request #88
Opened 2022-03-16 11:05 UTC by Ayo-lextego

2022-03-16 11:25 UTC, vorsterk requested changes
Hey Ayo please can you use variables for the URLS for arango and the endpoints

ie: const arangourl = pm.environment.get('arangourl');
     '${arangourl}/_db/pseudonyms/_api/cursor'
{{baseUrl}}/function/off-rule-048-rel-1-0-0/execute
{{baseUrl}}/function/off-typology-processor-rel-1-0-0                   etc.....

2022-03-17 06:48 UTC, johanfol requested changes

2022-03-17 06:48 UTC, johanfol commented on Rule-048.postman_collection.json
> +									"        url: 'https://frmarango.sybrin.com/_db/transactionHistory/_api/cursor',",
please use internal DB names throughout

2022-03-22 06:24 UTC, uche-lextego commented on Rule-048.postman_collection.json
> +									"        url: 'https://frmarango.sybrin.com/_db/pseudonyms/_api/cursor',",
@Ayo-lextego , please change to internal url here.

2022-03-23 07:18 UTC, vorsterk approved these changes

2022-04-12 12:36 UTC, johanfol requested changes

2022-04-12 12:36 UTC, johanfol commented on Rule-048.postman_collection.json
> +							"raw": "http://arango.development:8529/_db/transactionHistory/_api/cursor",
More urls instead of variables.

2022-04-20 09:00 UTC, johanfol approved these changes

2022-04-20 11:35 UTC, merged