Add rule 034 postman tests
ActioFRM/postman pull request #90
Opened 2022-03-17 11:40 UTC by thankgod-lextego

2022-03-21 08:25 UTC, uche-lextego requested changes
Well done @thankgod-lextego on this test. Please make use of variables for frm.faas URLs, gateway URL and arango urls.

2022-03-21 08:25 UTC, uche-lextego commented on Rule-034-tests.postman_collection.json
> +                  "    url: `http://arango.development:8529/_db/networkmap/_api/cursor`,\r",
Please add the ${arangourl} variable here

2022-03-21 08:25 UTC, uche-lextego commented on Rule-034-tests.postman_collection.json
> +                  "            \"host\": `http://gateway.openfaas:8080/function/off-transaction-aggregation-decisioning-processor-rel-1-0-0`,\r",
Use Variable instead of http://gateway.openfaas:8080

2022-03-21 08:25 UTC, uche-lextego commented on Rule-034-tests.postman_collection.json
> +              "raw": "http://gateway.openfaas:8080/function/off-transaction-monitoring-service-rel-1-0-0/transfer-response",
Here too

2022-03-23 07:19 UTC, vorsterk approved these changes

2022-04-07 08:01 UTC, uche-lextego approved these changes
LGTM

2022-04-07 08:03 UTC, merged